### ISSUE TITLE
CONSTRUCT queries are not supported

### ISSUE THREAD

**Issue by rubensworks** [joachimvh/SPARQLAlgebra.js#7]
Parsing this query: `CONSTRUCT { ?x ?y ?z } WHERE { ?x ?y ?z}`

Produces the following error:
```
/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:658
    if (query.queryType === 'ASK' || query.variables.indexOf('*') >= 0)
                                                    ^

TypeError: Cannot read property 'indexOf' of undefined
    at translateAggregates (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:658:53)
    at Object.translate (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/lib/sparqlAlgebra.js:143:11)
    at Object.<anonymous> (/Users/rtaelman/Documents/UGent/nosync/comunica/node_modules/sparqlalgebrajs/bin/sparqlalgebrajs.js:17:44)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
```

**Comment by joachimvh** [comment]
Yea, construct queries are still on the TODO list (technically algebra is only defined for select so will have to see what Jena does there).

**Comment by joachimvh** [comment]
The thing Jena does btw is just drop the entire construct part and just keep the where part as in a select query. I might add a new construct operator that keeps both.

**Comment by rubensworks** [comment]
Dropping the construct part doesn't sound particularly useful :-)

AFAIK constructs only support simple graphs, right? So perhaps it can be as simple as adding another bgp element for this clause?

**Comment by joachimvh** [comment]
Yea, would have to check the spec to be sure but I think so too, so would just be an operator that has the bgps as 1 parameter and the where clause as another one
